-- Run this entire file in Supabase SQL Editor
create table if not exists public.websites (
 id bigint generated by default as identity primary key,
 title text not null,
 category text not null,
 description text default '',
 image text default '',
 url text default '#',
 active boolean not null default true,
 featured boolean not null default false,
 created_at timestamptz not null default now()
);
create table if not exists public.site_settings (
 key text primary key,
 value text not null default '',
 updated_at timestamptz not null default now()
);
alter table public.websites enable row level security;
alter table public.site_settings enable row level security;
drop policy if exists "public active websites" on public.websites;
create policy "public active websites" on public.websites for select to anon,authenticated using (active=true);
drop policy if exists "authenticated all websites" on public.websites;
create policy "authenticated all websites" on public.websites for all to authenticated using(true) with check(true);
drop policy if exists "public settings" on public.site_settings;
create policy "public settings" on public.site_settings for select to anon,authenticated using(true);
drop policy if exists "authenticated settings" on public.site_settings;
create policy "authenticated settings" on public.site_settings for all to authenticated using(true) with check(true);
insert into public.site_settings(key,value) values
('phone','9654885119'),
('message','Hi, I''m interested in a website demo. Please share the details.'),
('logo','Deepak Web Studio'),('color','#6c5ce7') on conflict(key) do nothing;
insert into public.websites(title,category,description,image,url,active,featured)
select * from (values
('Luxe Hair Studio','Salon','Elegant salon website with services, gallery and booking CTA.','https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=900&q=80','#',true,false),
('The Grand Stay','Hotel','Luxury hotel landing page with rooms, amenities and enquiry.','https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80','#',true,false),
('Casa Verde','Restaurant','Premium restaurant showcase with menu and reservation CTA.','https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80','#',true,false),
('CarePlus Clinic','Doctor','Clean healthcare website for doctors and clinics.','https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=900&q=80','#',true,false),
('FitForge','Gym','Bold fitness website with programs, trainers and contact.','https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80','#',true,false),
('Urban Realty','Real Estate','Modern property showcase with listings and enquiry.','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80','#',true,false)
) v(title,category,description,image,url,active,featured) where not exists(select 1 from public.websites);
