-- Deepak Web Studio FINAL Supabase setup
create table if not exists public.demos (
 id bigint generated by default as identity primary key,
 title text not null, category text not null, description text default '',
 image text, url text, active boolean not null default true,
 featured boolean not null default false, created_at timestamptz not null default now()
);
create table if not exists public.reviews (
 id bigint generated by default as identity primary key,
 name text not null, project text default '',
 rating integer not null default 5 check (rating between 1 and 5),
 text text not null, approved boolean not null default false,
 created_at timestamptz not null default now()
);
create table if not exists public.site_settings (
 key text primary key, value text not null default '',
 updated_at timestamptz not null default now()
);
alter table public.demos enable row level security;
alter table public.reviews enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "public_read_active_demos" on public.demos;
create policy "public_read_active_demos" on public.demos for select to anon,authenticated using(active=true);
drop policy if exists "authenticated_manage_demos" on public.demos;
create policy "authenticated_manage_demos" on public.demos for all to authenticated using(true) with check(true);

drop policy if exists "public_read_approved_reviews" on public.reviews;
create policy "public_read_approved_reviews" on public.reviews for select to anon,authenticated using(approved=true);
drop policy if exists "authenticated_manage_reviews" on public.reviews;
create policy "authenticated_manage_reviews" on public.reviews for all to authenticated using(true) with check(true);

drop policy if exists "public_read_settings" on public.site_settings;
create policy "public_read_settings" on public.site_settings for select to anon,authenticated using(true);
drop policy if exists "authenticated_manage_settings" on public.site_settings;
create policy "authenticated_manage_settings" on public.site_settings for all to authenticated using(true) with check(true);

insert into public.site_settings(key,value) values
('phone','9654885119'),
('message','Hi, I am interested in a website demo. Please share the details.'),
('logo','Deepak Web Studio')
on conflict(key) do nothing;
